-- Guía EV HCFB: registrar consultas anónimas
create table if not exists public.consultas_medicamentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  medicamento_id text,
  medicamento text not null,
  categoria text,
  riesgo text,
  plataforma text,
  user_agent text
);

alter table public.consultas_medicamentos enable row level security;

drop policy if exists "insert consultas anonimas" on public.consultas_medicamentos;
create policy "insert consultas anonimas"
on public.consultas_medicamentos
for insert
to anon
with check (true);

drop policy if exists "leer consultas anonimas" on public.consultas_medicamentos;
create policy "leer consultas anonimas"
on public.consultas_medicamentos
for select
to anon
using (true);

create or replace function public.top_medicamentos(limite int default 8)
returns table(medicamento text, count bigint)
language sql
stable
as $$
  select cm.medicamento, count(*)::bigint
  from public.consultas_medicamentos cm
  group by cm.medicamento
  order by count(*) desc, cm.medicamento asc
  limit limite;
$$;


-- Universidad Mayor v13: campos académicos en consultas
alter table public.consultas_medicamentos add column if not exists institucion text;
alter table public.consultas_medicamentos add column if not exists anio_rol text;
alter table public.consultas_medicamentos add column if not exists campo_clinico text;
alter table public.consultas_medicamentos add column if not exists contexto text;

-- Registros de ingreso académico
create table if not exists public.ingresos_academicos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  institucion text,
  anio_rol text,
  campo_clinico text,
  contexto text,
  plataforma text,
  user_agent text
);
alter table public.ingresos_academicos enable row level security;
drop policy if exists "insert ingresos academicos anon" on public.ingresos_academicos;
create policy "insert ingresos academicos anon" on public.ingresos_academicos
for insert to anon with check (true);
drop policy if exists "leer ingresos academicos anon" on public.ingresos_academicos;
create policy "leer ingresos academicos anon" on public.ingresos_academicos
for select to anon using (true);

-- Comentarios por medicamento
create table if not exists public.comentarios_medicamentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  medicamento_id text,
  medicamento text,
  categoria text,
  comentario text,
  institucion text,
  anio_rol text,
  campo_clinico text,
  contexto text
);
alter table public.comentarios_medicamentos enable row level security;
drop policy if exists "insert comentarios anon" on public.comentarios_medicamentos;
create policy "insert comentarios anon" on public.comentarios_medicamentos
for insert to anon with check (true);
drop policy if exists "leer comentarios anon" on public.comentarios_medicamentos;
create policy "leer comentarios anon" on public.comentarios_medicamentos
for select to anon using (true);

-- Resultados de quiz académico
create table if not exists public.quiz_resultados (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  score int,
  total int,
  porcentaje int,
  institucion text,
  anio_rol text,
  campo_clinico text,
  contexto text
);
alter table public.quiz_resultados enable row level security;
drop policy if exists "insert quiz anon" on public.quiz_resultados;
create policy "insert quiz anon" on public.quiz_resultados
for insert to anon with check (true);
drop policy if exists "leer quiz anon" on public.quiz_resultados;
create policy "leer quiz anon" on public.quiz_resultados
for select to anon using (true);
